version: '3'
services: 
  nest-api:
    build:
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run start:prod

  db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine