version: '3.8'
services: 
  nest-api:
    build:
      context: .
    ports:
      - ${API_PORT}:${APP_PORT}
    depends_on:
        - db
    environment:
      PORT: ${APP_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}


  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/data/db
  
  redis:
    image: redis:alpine

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data: